#!/usr/bin/env python3
"""Generate kernel/src/gui/web_font_data.rs: the browser's page fonts.

Usage: scripts/gen-web-font.py > kernel/src/gui/web_font_data.rs

Uses the rasteriser in gen-aa-font.py (Pillow and the DejaVu fonts in
fonts/). The desktop's own fonts stay in font_data.rs.
"""
import importlib.util
import os
import sys

sys.dont_write_bytecode = True

here = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("gen_aa_font", os.path.join(here, "gen-aa-font.py"))
aa = importlib.util.module_from_spec(spec)
spec.loader.exec_module(aa)

TEXT = aa.LATIN + aa.CYRILLIC + [
    (0x2013, 0x2014), (0x2018, 0x201E), (0x2020, 0x2022), (0x2026, 0x2026),
    (0x2030, 0x2030), (0x2039, 0x203A), (0x20AC, 0x20AC), (0x2116, 0x2116),
    (0x2122, 0x2122), (0x2190, 0x2193), (0x2212, 0x2212), (0x25B2, 0x25BC),
]
HEADINGS = aa.LATIN + aa.CYRILLIC + [(0x2013, 0x2014), (0x2018, 0x201E), (0x2026, 0x2026)]

FONTS = [
    ("PAGE", "fonts/DejaVuSans.ttf", 16, TEXT),
    ("PAGE_BOLD", "fonts/DejaVuSans-Bold.ttf", 16, TEXT),
    ("H1", "fonts/DejaVuSans-Bold.ttf", 30, HEADINGS),
    ("H2", "fonts/DejaVuSans-Bold.ttf", 24, HEADINGS),
]


def main():
    os.chdir(os.path.join(here, ".."))
    print("// Generated by scripts/gen-web-font.py from the DejaVu fonts in fonts/.")
    print("// DejaVu fonts: Bitstream Vera license, see fonts/LICENSE.dejavu.")
    print("// Do not edit by hand.")
    print()
    print("use super::text::{Font, Glyph};")
    for f in FONTS:
        print()
        print(aa.font_rs(*f))


if __name__ == "__main__":
    sys.exit(main())
